### ISSUE TITLE
Fly False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Olexorus/WitherAC#18] opened 2019-08-19 21:17 UTC
building up in the end or nether or in the overworld over like 120 on the y will false fly idk why heres a video of it https://streamable.com/2s1xy

**Comment by Olexorus** [comment] 2019-08-21 20:21
Duplicate of https://github.com/Olexorus/WitherAC/issues/14

**Closed** 2019-08-21 21:33 UTC
Labels: false positive, probably fixed
