### ISSUE TITLE
Wither AC doesn't know 1.14.4 Citizens. But does know 1.14.3 (0.13.0 - 0.14.0)

### ISSUE THREAD

**Issue by VanillaChan6571** [Olexorus/WitherAC#1] opened 2019-07-29 04:26 UTC
When upgrading from 1.14.3 to 1.14.4 it seems WAC doesn't know a citizen NPC.

https://pastebin.com/Eph5vU9v (Logged from logs)

Otherwise it works fine as attended.

**Comment by Olexorus** [comment] 2019-07-29 09:06
I've never used Citizens myself and don't know much about it. Citizens adds fake players to the world, right? The problem is that WitherAC creates data for every player when they join, however if they don't join but are created through code, then that happens.

I could change it to automatically create data when none is found, but that would basically mean that Citizens NPCs are also checked, which wouldn't make much sense. Do you know of any easy way to differentiate between real players and NPCs?

And can NPCs have permissions? Because then you could give them the wac.bypass permission as a workaround.

**Comment by FinalPacket** [comment] 2019-07-29 09:34
@Olexorus are you storing Player rather than UUIDs? If so that creates problems; memory leaks, etc.

**Comment by Olexorus** [comment] 2019-07-29 09:40
No that wouldn't even work (for example when someone leaves and reenters the server), I'm using UUIDs as keys

**Comment by Olexorus** [comment] 2019-07-29 12:43
I just looked at the Citizens API, it's actually really easy to check if a player is a NPC, this should be fixed in the next version.

**Comment by Olexorus** [comment] 2019-07-29 14:45
Please check if it's still a problem on 0.12.2, it should be fixed.

**Comment by VanillaChan6571** [comment] 2019-08-01 21:13
This still occurs in 0.13.0

**Comment by Olexorus** [comment] 2019-08-02 09:10
I think I know why it's still happening, I'll make another attempt at fixing it in 0.14.1

**Comment by Olexorus** [comment] 2019-08-12 15:33
Sorry I was so inactive recently, 0.14.1 (will be released later today) should have Citizens compatibility.

**Comment by Olexorus** [comment] 2019-08-12 18:25
I just released 0.14.1 which should fix this.

Please reopen if it's still an issue.

**Closed by Olexorus** 2019-08-12 18:25 UTC
Labels: bug
