### ISSUE TITLE
Why isnt there an elytraflight check?

### ISSUE THREAD

**Issue by rasputinea** [Olexorus/WitherAC#38] opened 2020-03-05 00:02 UTC
Not having an elytraflight check defeats the whole purpose of all of witheracs movement checks, one can simply get an elytra and fly max flight speed everywhere.

**Comment by Olexorus** [comment] 2020-03-11 13:05
On a lot of servers, Elytras aren't easily accessible, so a normal Fly check is still really useful. However I understand how important an Elytra check is, and I plan to add it in the future. The problem is that it's completely different from the normal fly check and it'll be a lot of work, that's why I haven't done it yet.

I've added it to my To-Do list on the Discord server and will close this issue here. Thank you for your feedback.

**Closed by Olexorus** 2020-03-11 13:05 UTC
