### ISSUE TITLE
Speed False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Olexorus/WitherAC#21] opened 2019-08-21 22:10 UTC
i was randomly making a animal farm and i got in and was sprinting around and it falsed speed cause the animals were pushing me faster then i should of been so i falsed speed https://streamable.com/h56yy

**Comment by Olexorus** [comment] 2019-10-13 09:08
I can reproduce it, but this would be really hard to fix, because pushing physics are weird, and I'd have to calculate it for every single entity, it would likely cost a lot of performance and make bypasses possible. Besides I don't think this happens often, so I won't fix this for now.

**Closed by Olexorus** 2019-10-13 09:08 UTC
